apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka
  annotations:
    strimzi.io/node-pools: "enabled"
    strimzi.io/kraft: "enabled"
    argocd.argoproj.io/sync-wave: "10"
spec:
  kafka:
    version: 4.1.1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      # Docker: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      offsets.topic.replication.factor: 1
      # Docker: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      transaction.state.log.min.isr: 1
      # Docker: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      transaction.state.log.replication.factor: 1
      # Docker: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      group.initial.rebalance.delay.ms: 0
      # Docker: default.replication.factor: 1
      default.replication.factor: 1
      # Docker: min.insync.replicas: 1
      min.insync.replicas: 1
      # Security & Maintenance (from previous steps)
      auto.create.topics.enable: false
      log.cleaner.enable: true
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
  # zookeeper:
  #   replicas: 1
  #   storage:
  #     type: ephemeral
  #   readinessProbe:
  #     initialDelaySeconds: 15
  #     timeoutSeconds: 5
  #   livenessProbe:
  #     initialDelaySeconds: 15
  #     timeoutSeconds: 5
  entityOperator:
    topicOperator: {}
    userOperator: {}