apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: messages
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  partitions: 3
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: notify-messages
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 3
  replicas: 1