apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: postgres
  labels:
    service: database
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: postgres
  labels:
    service: database
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
        service: database
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-credentials
            - configMapRef:
                name: postgres-config
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U postgres -d messages
            initialDelaySeconds: 10 # start_period
            periodSeconds: 10       # interval
            timeoutSeconds: 5       # timeout
            failureThreshold: 5     # retries
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U postgres -d messages
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgres
  labels:
    service: database
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  selector:
    app: postgres
  ports:
    - port: 5432